version: "3.9"

services:
  front1:
    build:
      context: ./front1
    ports:
      - 80:80
    volumes:
      - type: volume
        source: front1www
        target: /var/www/html/site

volumes:
  front1www
