version: "3.9"

services:
  front1:
    container_name: "front1-${BUILD_NUMBER}"
    privileged: true
    build:
      context: ./front1
    ports:
      - 80:80
    volumes:
      - type: volume
        source: front1www5
        target: /var/www/html/site
  back1:
    container_name: "back1-${BUILD_NUMBER}"
    hostname: back1-add
    privileged: true
    build:
      context: ./back1
    ports:
      - "9000"
    volumes:
      - front1www5:/var/www/html/site
    command: php-fpm -F
  back2:
    container_name: "back2-${BUILD_NUMBER}"
    hostname: back2-multiply
    privileged: true
    build:
      context: ./back2
    ports:
      - "9001"
    volumes:
      - front1www5:/var/www/html/site
    command: php-fpm -F

volumes:
  front1www5:
