version: "3.9"

services:
  front1:
    container_name: "front1-${BUILD_NUMBER}"
    build:
      context: ./front1
    ports:
      - 80:80
    volumes:
      - type: volume
        source: front1www1
        target: /var/www/html/site
  back1:
    container_name: "back1-${BUILD_NUMBER}"
    build:
      context: ./back
    ports:
      - "9000"
    volumes:
      - front1www1:/var/www/html/site
    command: php -S="0.0.0.0:9000" -t="/var/www/html/site"
  back2:
    container_name: "back2-${BUILD_NUMBER}"
    build:
      context: ./back
    ports:
      - "9001"
    volumes:
      - front1www1:/var/www/html/site
    command: php -S="0.0.0.0:9001" -t="/var/www/html/site"

volumes:
  front1www1:
